FROM python:3.12.4-bullseye

ENV CONFIG_MODE=production

WORKDIR /usr/src/app

RUN python -m venv .venv
RUN . .venv/bin/activate

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD ["python", "app.py"]

EXPOSE 8080
